In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import warnings
warnings.filterwarnings('ignore')

In [2]:
d1 = pd.read_csv('data/Customer_and_bank details_p1.csv')

In [3]:
d1[:2]

Customer_id  age       job  marital    education  default housing loan  \
0            1   56  services  married  high.school       no      no  yes   
1            2   45  services  married     basic.9y  unknown      no   no   

  Region_Code State_Code City_Code  
0           3         S1        C1  
1           3         S1        C1

In [4]:
d1.shape

(37084, 11)

In [5]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37084 entries, 0 to 37083
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer_id  37084 non-null  int64 
 1   age          37084 non-null  int64 
 2   job          37084 non-null  object
 3   marital      37084 non-null  object
 4   education    37084 non-null  object
 5   default      37084 non-null  object
 6   housing      37084 non-null  object
 7   loan         37084 non-null  object
 8   Region_Code  37084 non-null  object
 9   State_Code   37084 non-null  object
 10  City_Code    37084 non-null  object
dtypes: int64(2), object(9)
memory usage: 3.1+ MB


In [6]:
d2 = pd.read_csv('data/Customer_campaign_details_p1.csv')

In [7]:
d2[:2]

Customer_id    contact month day_of_week  duration  campaign  pdays  \
0            1  telephone   may         mon       307         1    999   
1            2  telephone   may         mon       198         1    999   

   previous     poutcome  
0         0  nonexistent  
1         0  nonexistent

In [8]:
d2.shape

(37084, 9)

In [9]:
d2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37084 entries, 0 to 37083
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer_id  37084 non-null  int64 
 1   contact      37084 non-null  object
 2   month        37084 non-null  object
 3   day_of_week  37084 non-null  object
 4   duration     37084 non-null  int64 
 5   campaign     37084 non-null  int64 
 6   pdays        37084 non-null  int64 
 7   previous     37084 non-null  int64 
 8   poutcome     37084 non-null  object
dtypes: int64(5), object(4)
memory usage: 2.5+ MB


In [10]:
d3 = pd.read_csv('data/Customer_Postal_Code_details.csv')

In [11]:
d3[:2]

customer_id  Postal Code
0            1        42420
1            2        42420

In [12]:
d3.shape

(37084, 2)

In [13]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37084 entries, 0 to 37083
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  37084 non-null  int64
 1   Postal Code  37084 non-null  int64
dtypes: int64(2)
memory usage: 579.6 KB


In [14]:
d3.rename(columns = {'customer_id' : 'Customer_id'}, inplace = True)

In [15]:
d3[:2]

Customer_id  Postal Code
0            1        42420
1            2        42420

In [16]:
d4 = pd.read_csv('data/City_Master.csv')

In [17]:
d4[:2]

City_Code    City_Name State_Code
0        C1    Henderson         S1
1        C2  Los Angeles         S2

In [18]:
d4.shape

(531, 3)

In [19]:
d4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   City_Code   531 non-null    object
 1   City_Name   531 non-null    object
 2   State_Code  531 non-null    object
dtypes: object(3)
memory usage: 12.6+ KB


In [20]:
d5 = pd.read_csv('data/Customer_Response_data_p1.csv')

In [21]:
d5[:2]

Customer_id   y
0            1  no
1            2  no

In [22]:
d5.shape

(37084, 2)

In [23]:
d5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37084 entries, 0 to 37083
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer_id  37084 non-null  int64 
 1   y            37084 non-null  object
dtypes: int64(1), object(1)
memory usage: 579.6+ KB


In [24]:
d6 = pd.read_csv('data/Customer_social_economic_data_p1.csv')

In [25]:
d6[:2]

Customer_id  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0            1           1.1          93.994          -36.4      4.857   
1            2           1.1          93.994          -36.4      4.857   

   nr.employed  
0       5191.0  
1       5191.0

In [26]:
d6.shape

(37084, 6)

In [27]:
d6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37084 entries, 0 to 37083
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Customer_id     37084 non-null  int64  
 1   emp.var.rate    37084 non-null  float64
 2   cons.price.idx  37084 non-null  float64
 3   cons.conf.idx   37084 non-null  float64
 4   euribor3m       37084 non-null  float64
 5   nr.employed     37084 non-null  float64
dtypes: float64(5), int64(1)
memory usage: 1.7 MB


In [28]:
d7 = pd.read_csv('data/Region_code_master.csv')

In [29]:
d7[:2]

Region_Name  Region_Code
0     Central            1
1        East            2

In [30]:
d7.shape

(5, 2)

In [31]:
d7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Region_Name  5 non-null      object
 1   Region_Code  5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes


In [32]:
d8 = pd.read_csv('data/State_Master.csv')

In [33]:
d8[:2]

State_Code  State_Name  Region_Code
0         S1    Kentucky            3
1         S2  California            4

In [34]:
d8.shape

(49, 3)

In [35]:
d8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   State_Code   49 non-null     object
 1   State_Name   49 non-null     object
 2   Region_Code  49 non-null     int64 
dtypes: int64(1), object(2)
memory usage: 1.3+ KB


In [36]:
# Joining Datasets

In [37]:
c1 = pd.merge(d1, d2, on='Customer_id', how='inner')

In [38]:
c1[:2]

Customer_id  age       job  marital    education  default housing loan  \
0            1   56  services  married  high.school       no      no  yes   
1            2   45  services  married     basic.9y  unknown      no   no   

  Region_Code State_Code City_Code    contact month day_of_week  duration  \
0           3         S1        C1  telephone   may         mon       307   
1           3         S1        C1  telephone   may         mon       198   

   campaign  pdays  previous     poutcome  
0         1    999         0  nonexistent  
1         1    999         0  nonexistent

In [39]:
c1.shape

(37084, 19)

In [40]:
c2 = pd.merge(c1, d3, on='Customer_id', how='inner')

In [41]:
c2[:2]

Customer_id  age       job  marital    education  default housing loan  \
0            1   56  services  married  high.school       no      no  yes   
1            2   45  services  married     basic.9y  unknown      no   no   

  Region_Code State_Code City_Code    contact month day_of_week  duration  \
0           3         S1        C1  telephone   may         mon       307   
1           3         S1        C1  telephone   may         mon       198   

   campaign  pdays  previous     poutcome  Postal Code  
0         1    999         0  nonexistent        42420  
1         1    999         0  nonexistent        42420

In [42]:
c2.shape

(37084, 20)

In [43]:
c3 = pd.merge(c2, d4, on=['City_Code','State_Code'], how='outer')

In [44]:
c3[:2]

Customer_id  age       job  marital    education  default housing loan  \
0            1   56  services  married  high.school       no      no  yes   
1            2   45  services  married     basic.9y  unknown      no   no   

  Region_Code State_Code  ...    contact month day_of_week duration  campaign  \
0           3         S1  ...  telephone   may         mon      307         1   
1           3         S1  ...  telephone   may         mon      198         1   

   pdays  previous     poutcome Postal Code  City_Name  
0    999         0  nonexistent       42420  Henderson  
1    999         0  nonexistent       42420  Henderson  

[2 rows x 21 columns]

In [45]:
c3.shape

(37084, 21)

In [46]:
c4 = pd.merge(c3, d5, on='Customer_id', how='inner')

In [47]:
c4[:2]

Customer_id  age       job  marital    education  default housing loan  \
0            1   56  services  married  high.school       no      no  yes   
1            2   45  services  married     basic.9y  unknown      no   no   

  Region_Code State_Code  ... month day_of_week duration campaign  pdays  \
0           3         S1  ...   may         mon      307        1    999   
1           3         S1  ...   may         mon      198        1    999   

   previous     poutcome  Postal Code  City_Name   y  
0         0  nonexistent        42420  Henderson  no  
1         0  nonexistent        42420  Henderson  no  

[2 rows x 22 columns]

In [48]:
c4.shape

(37084, 22)

In [49]:
c5 = pd.merge(c4, d6, on='Customer_id', how='inner')

In [50]:
c5[:2]

Customer_id  age       job  marital    education  default housing loan  \
0            1   56  services  married  high.school       no      no  yes   
1            2   45  services  married     basic.9y  unknown      no   no   

  Region_Code State_Code  ... previous     poutcome Postal Code  City_Name  \
0           3         S1  ...        0  nonexistent       42420  Henderson   
1           3         S1  ...        0  nonexistent       42420  Henderson   

    y  emp.var.rate  cons.price.idx  cons.conf.idx euribor3m  nr.employed  
0  no           1.1          93.994          -36.4     4.857       5191.0  
1  no           1.1          93.994          -36.4     4.857       5191.0  

[2 rows x 27 columns]

In [51]:
c5.shape

(37084, 27)

In [ ]:
c6 = pd.merge(c5, d7, on='Region_Code', how='inner')

In [57]:
# You are trying to merge on object and int64 columns for key 'Region_Code'.

In [54]:
d7['Region_Code'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [55]:
c5['Region_Code'].unique()

array(['3', 'Na', '4', '1', '2'], dtype=object)

In [56]:
c5['Region_Code'] = c5['Region_Code'].replace('Na', '5').astype('int64')

In [58]:
c6 = pd.merge(c5, d7, on='Region_Code', how='inner')

In [61]:
c6.shape

(37084, 28)

In [62]:
# c6 has the 'Region_Code' == 5 but d8 has only till 4

In [63]:
d8['Region_Code'].unique()

array([3, 4, 1, 2], dtype=int64)

In [64]:
c6['Region_Code'].unique()

array([3, 5, 4, 1, 2], dtype=int64)

In [65]:
c6 = c6[c6['Region_Code'] != 5]

In [66]:
c6['Region_Code'].unique()

array([3, 4, 1, 2], dtype=int64)

In [67]:
df = pd.merge(c6, d8, on=['State_Code','Region_Code'], how='inner')

In [68]:
df.shape

(37024, 29)

In [69]:
df.head()

Customer_id  age          job  marital          education  default housing  \
0            1   56     services  married        high.school       no      no   
1            2   45     services  married           basic.9y  unknown      no   
2          539   32       admin.   single  university.degree       no      no   
3          540   36     services  married        high.school       no      no   
4          997   31  blue-collar  married           basic.9y       no      no   

  loan  Region_Code State_Code  ... Postal Code  City_Name   y emp.var.rate  \
0  yes            3         S1  ...       42420  Henderson  no          1.1   
1   no            3         S1  ...       42420  Henderson  no          1.1   
2   no            3         S1  ...       42420  Henderson  no          1.1   
3   no            3         S1  ...       42420  Henderson  no          1.1   
4   no            3         S1  ...       42420  Henderson  no          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed Region_Name  \
0          93.994          -36.4      4.857       5191.0       South   
1          93.994          -36.4      4.857       5191.0       South   
2          93.994          -36.4      4.857       5191.0       South   
3          93.994          -36.4      4.857       5191.0       South   
4          93.994          -36.4      4.856       5191.0       South   

   State_Name  
0    Kentucky  
1    Kentucky  
2    Kentucky  
3    Kentucky  
4    Kentucky  

[5 rows x 29 columns]

In [70]:
# Rename column name to lower case
df.columns = df.columns.str.lower()

In [71]:
df[:2]

customer_id  age       job  marital    education  default housing loan  \
0            1   56  services  married  high.school       no      no  yes   
1            2   45  services  married     basic.9y  unknown      no   no   

   region_code state_code  ... postal code  city_name   y emp.var.rate  \
0            3         S1  ...       42420  Henderson  no          1.1   
1            3         S1  ...       42420  Henderson  no          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed region_name  \
0          93.994          -36.4      4.857       5191.0       South   
1          93.994          -36.4      4.857       5191.0       South   

   state_name  
0    Kentucky  
1    Kentucky  

[2 rows x 29 columns]

In [72]:
# Check for duplicate columns
df_transposed = df.T
duplicate_columns = df_transposed[df_transposed.duplicated()].index
print("Duplicate columns:", duplicate_columns)

Duplicate columns: Index([], dtype='object')


In [73]:
df.to_csv('dataset.csv', index=False)